import json
import logging
from typing import Dict
from api.schemas import BugReport

logger = logging.getLogger(__name__)

class ReportEngine:
    """
    Transforms structured AI output into specialized formats 
    for engineering project management tools.
    """

    @staticmethod
    def to_markdown(report: BugReport) -> str:
        """
        Converts the BugReport schema into a professional Markdown 
        template suitable for JIRA descriptions or GitHub Issues.
        """
        steps = "\n".join([f"{i+1}. {step}" for i, step in enumerate(report.steps_to_reproduce)])
        
        markdown_template = f"""
# [BUG] {report.title}
**Severity:** {report.severity}

## 📝 Description
{report.description}

## 🚀 Steps to Reproduce
{steps}

## 🎯 Expected vs Actual
**Expected:** {report.expected_behavior}
**Actual:** {report.actual_behavior}

## 💡 AI Suggested Fix
{report.suggested_fix if report.suggested_fix else "No automated fix suggested."}

---
*Generated by The Lazy QA Agent - Autonomous Bug Reporting Engine*
        """
        return markdown_template.strip()

    @staticmethod
    def to_jira_json(report: BugReport) -> Dict:
        """
        Formats the bug report for direct injection into JIRA's REST API.
        This proves the 'streamline deployment' and 'integrated workflow' claims.
        """
        return {
            "fields": {
                "project": {"key": "QA"},
                "summary": f"[AI-Generated] {report.title}",
                "description": ReportEngine.to_markdown(report),
                "issuetype": {"name": "Bug"},
                "priority": {"name": report.severity}
            }
        }